version: '3.8'

services:
  web:
    build: .
    container_name: laravel_vue_app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - php
      - nginx

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - ./deploy/nginx/default.conf:/etc/nginx/sites-available/default
    networks:
      - app-network
    depends_on:
      - php

  node:
    image: node:16
    container_name: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: sh -c "npm install && npm run dev"
    
networks:
  app-network:
    driver: bridge
